# Generated by Django 4.2.7 on 2023-12-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('assignDate', models.DateField()),
            ],
        ),
    ]
